version: '3'
    
services:
    db:
        image: postgres
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - "5432"
        
    web:
        build: .
        command: python3 ./runningTask/manage.py runserver 0.0.0.0:8000
        volumes:
        - .:/code
        ports:
        - "8000:8000"
        depends_on:
        - db
        links:
            - db:db